CREATE DATABASE FinalSis457Rvu;

USE [master]
GO
CREATE LOGIN [usrfinal] WITH PASSWORD=N'12345678', 
   DEFAULT_DATABASE=[FinalSis457Rvu], 
   CHECK_EXPIRATION=OFF, 
   CHECK_POLICY=ON
GO
USE [FinalSis457Rvu]
GO
CREATE USER [usrfinal] FOR LOGIN [usrfinal]
GO
USE [FinalSis457Rvu]
GO
ALTER ROLE [db_owner] ADD MEMBER [usrfinal]
GO

CREATE TABLE Serie (
  id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  titulo VARCHAR(250) NOT NULL,
  sinopsis VARCHAR(5000) NOT NULL,
  director VARCHAR(100) NOT NULL,
  duracion INT NOT NULL DEFAULT 0,
  fechaEstreno DATE NULL DEFAULT GETDATE(),
  usuarioRegistro VARCHAR(12) NULL DEFAULT SUSER_SNAME(),
  registroActivo BIT NOT NULL DEFAULT 1
);

CREATE TABLE Usuario (
  id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
  usuario VARCHAR(12) NOT NULL,
  clave VARCHAR(250) NOT NULL,
  rol VARCHAR(20) NOT NULL,
  registroActivo BIT NOT NULL DEFAULT 1
  );